apiVersion: v2
name: polars
description: Distributed query execution engine for Polars

type: application

version: 0.0.8
appVersion: "20251203"
deprecated: false

dependencies: []

home: https://pola.rs
sources:
  - https://github.com/pola-rs/polars
  - https://github.com/polars-inc/helm-charts
keywords:
  - polars
  - distributed-computing
  - query-engine
annotations:
  category: Analytics

maintainers:
  - name: Polars
    email: developers@polars.tech
    url: https://github.com/polars-inc
