apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polars.worker.fullname" . }}
  labels:
    {{ include "polars.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.worker.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{ include "polars.selectorLabels" . | nindent 6 }}
  strategy:
    type: "Recreate"
  template:
    metadata:
{{- with .Values.worker.deployment.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/component: worker
        {{ include "polars.labels" . | nindent 8 }}
{{- with .Values.worker.deployment.podLabels }}
        {{ toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- with .Values.worker.deployment.dnsPolicy }}
      dnsPolicy: {{ . }}
{{- end }}
{{- with .Values.worker.deployment.dnsConfig }}
      dnsConfig:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.schedulerName }}
      schedulerName: {{ . }}
{{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "polars.worker.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.worker.serviceAccount.automount }}
{{- with .Values.worker.deployment.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.hostAliases }}
      hostAliases:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{ if .Values.runtime.composed.enabled }}
      initContainers:
        - name: release
  {{- with .Values.worker.deployment.distContainer.securityContext }}
          securityContext:
          {{ toYaml . | nindent 12 }}
  {{- end }}
          image: "{{ .Values.runtime.composed.dist.repository }}:{{ .Values.runtime.composed.dist.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runtime.composed.dist.pullPolicy }}
          command:
            - /bin/cp
          args:
            - -a
            - /opt/.
            - /emptydir
  {{- with .Values.worker.deployment.distContainer.resources }}
          resources:
          {{ toYaml . | nindent 12 }}
  {{- end }}
          volumeMounts:
            - name: release-data
              mountPath: /emptydir
{{- end }}
      containers:
        - name: worker
{{- with .Values.worker.deployment.runtimeContainer.securityContext }}
          securityContext:
            {{ toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.runtime.composed.enabled }}
          image: "{{ .Values.runtime.composed.runtime.repository }}:{{ .Values.runtime.composed.runtime.tag }}"
          imagePullPolicy: {{ .Values.runtime.composed.runtime.pullPolicy }}
          command:
            - /emptydir/setup.sh
          args:
            - /emptydir/bin/pc-cublet
            - service
          workingDir: /tmp
{{- end }}
{{- if .Values.runtime.prebuilt.enabled }}
          image: "{{ .Values.runtime.prebuilt.runtime.repository }}:{{ .Values.runtime.prebuilt.runtime.tag }}"
          imagePullPolicy: {{ .Values.runtime.prebuilt.runtime.pullPolicy }}
{{- end }}
          ports:
            - name: worker-flight
              containerPort: 5052
              protocol: TCP
            - name: worker-service
              containerPort: 5053
              protocol: TCP
{{- with .Values.worker.deployment.runtimeContainer.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
{{- end }}
          env:
            - name: POLARS_EXTRAS
              value: {{ .Values.runtime.composed.polarsExtras | default "" }}
            - name: POLARS_WHL_DIR
              value: /emptydir/whl
{{- if .Values.runtime.composed.enabled }}
  {{- if .Values.runtime.composed.requirements }}
            - name: PYTHON_REQUIREMENTS
              value: /requirements.txt
  {{- end }}
{{- end }}
            - name: UV_PATH
              value: "/emptydir/bin/uv"
{{- if .Values.telemetry.otlpEndpoint }}
            - name: OTLP_ENDPOINT
              value: {{ .Values.telemetry.otlpEndpoint | quote }}
{{- end }}
            - name: OTEL_SERVICE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POLARS_SKIP_DSL_HASH_VERIFICATION
              value: "1"
{{- if .Values.license }}
            - name: PC_CUBLET__license
              value: "/license/license.json"
{{- end }}
            - name: PC_CUBLET__static_leader__leader_instance_id
              value: "{{ include "polars.worker.fullname" . }}-0"
            - name: PC_CUBLET__static_leader__scheduler_service__public_addr__hostname
              value: "{{ include "polars.scheduler-internal.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: PC_CUBLET__static_leader__scheduler_service__public_addr__port
              value: "5050"
            - name: PC_CUBLET__static_leader__observatory_service__public_addr__hostname
              value: "{{ include "polars.scheduler-internal.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: PC_CUBLET__static_leader__observatory_service__public_addr__port
              value: "5049"
            - name: PC_CUBLET__cluster_id
              value: {{ include "polars.clusterId" . | quote }}
            - name: PC_CUBLET__instance_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: PC_CUBLET__monitoring__enabled
              value: "true"
            - name: PC_CUBLET__worker__enabled
              value: "true"
            - name: PC_CUBLET__worker__task_service__public_addr__ip
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PC_CUBLET__worker__shuffle_service__public_addr__ip
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PC_CUBLET__worker__heartbeat_period
              value: "{{ .Values.workerHeartbeatIntervalSecs }}s"
{{- if .Values.shuffleData.s3.enabled }}
            - name: PC_CUBLET__worker__shuffle_location__s3__url
              value: {{ .Values.shuffleData.s3.endpoint | quote }}
  {{- range .Values.shuffleData.s3.options }}
    {{- if eq .name "url" }}
      {{ fail "Name 'url' found in .Values.anonymousResults.s3.options Please use .Values.shuffleData.s3.endpoint instead" }}
    {{- end }}
            - name: PC_CUBLET__worker__shuffle_location__s3__{{ .name | required "missing .Values.shuffleData.s3.options[x].name" }}
    {{- if .value }}
              value: {{ .value | quote }}
    {{- else if .valueFrom }}
              valueFrom:
                {{ toYaml .valueFrom | nindent 16 }}
    {{- end }}
  {{- end }}
{{- else }}
            - name: PC_CUBLET__worker__shuffle_location__local__path
              value: /app/shuffle_data/shuffle_data
{{- end }}
            - name: PLC_LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: RUST_BACKTRACE
              value: "full"
            - name: POLARS_TEMP_DIR
              value: /app/temporary_data/temporary_data
{{- if .Values.acceptEula }}
            - name: POLARS_EULA_ACCEPTED
              value: "yes"
{{- end }}
{{- with .Values.worker.deployment.runtimeContainer.env }}
            {{ toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.worker.deployment.runtimeContainer.lifecycleHooks }}
          lifecycle:
            {{ toYaml .Values.worker.deployment.runtimeContainer.lifecycleHooks | nindent 12 }}
{{- end }}
          # TODO: lifenessProbe
          # TODO: readinessProbe:
{{- with .Values.worker.deployment.runtimeContainer.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
{{- with .Values.license }}
            - name: license
              mountPath: /license/
{{- end }}
{{- if .Values.runtime.composed.enabled }}
  {{- if .Values.runtime.composed.requirements }}
            - name: requirements-txt
              mountPath: /requirements.txt
              subPath: requirements.txt
  {{- end }}
            - name: tmp-data
              mountPath: /tmp
            - name: release-data
              mountPath: /emptydir
{{- end }}
            - name: temporary-data
              mountPath: /app/temporary_data
{{- if not .Values.shuffleData.s3.enabled }}
            - name: shuffle-data
              mountPath: /app/shuffle_data
{{- end }}
{{- with .Values.worker.deployment.runtimeContainer.volumeMounts }}
            {{ toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.worker.deployment.priorityClassName }}
      priorityClassName: {{ .Values.worker.deployment.priorityClassName | quote }}
{{- end }}
{{- if .Values.worker.deployment.runtimeClassName }}
      runtimeClassName: {{ .Values.worker.deployment.runtimeClassName | quote }}
{{- end }}
      volumes:
        - name: temporary-data
{{- if .Values.temporaryData.ephemeralVolumeClaim.enabled }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.temporaryData.ephemeralVolumeClaim.storageClassName }}
                resources:
                  requests:
                    storage: {{ .Values.temporaryData.ephemeralVolumeClaim.size }}
{{- else }}
          emptyDir: {}
{{- end }}
{{- if not .Values.shuffleData.s3.enabled }}
        - name: shuffle-data
  {{- if .Values.shuffleData.ephemeralVolumeClaim.enabled }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.shuffleData.ephemeralVolumeClaim.storageClassName }}
                resources:
                  requests:
                    storage: {{ .Values.shuffleData.ephemeralVolumeClaim.size }}
  {{- else }}
          emptyDir: {}
  {{- end }}
{{- end }}
{{- with .Values.license }}
        - name: license
          secret:
            secretName: {{ required ".Values.license.secretName is required" .secretName | quote }}
            items:
              - key: {{ required ".Values.license.secretProperty is required" .secretProperty | quote }}
                path: license.json
{{- end }}
{{- if .Values.runtime.composed.enabled }}
  {{- if .Values.runtime.composed.requirements }}
        - name: requirements-txt
          configMap:
            name: {{ include "polars.fullname" . }}-requirements-txt
            items:
              - key: requirementsTxt
                path: requirements.txt
  {{- end }}
        - name: tmp-data
          emptyDir: {}
        - name: release-data
          emptyDir: {}
{{- end }}
{{- with .Values.worker.deployment.volumes }}
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.worker.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ toYaml . | nindent 8 }}
{{- end }}
      hostNetwork: {{ .Values.worker.deployment.hostNetwork }}
