apiVersion: v1
kind: Service
metadata:
  name: {{ include "polars.worker-headless.fullname" . }}
  labels:
    {{- include "polars.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports: []
  selector:
    {{- include "polars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
