apiVersion: v1
kind: Service
metadata:
  name: {{ include "polars.observatory.fullname" . }}
  labels:
    {{- include "polars.labels" . | nindent 4 }}
  annotations:
{{- with .Values.scheduler.services.observatory.annotations }}
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.scheduler.services.observatory.type }}
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: obser-rest
  selector:
    {{- include "polars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
