apiVersion: v1
kind: Service
metadata:
  name: {{ include "polars.scheduler-internal.fullname" . }}
  labels:
    {{- include "polars.labels" . | nindent 4 }}
  annotations:
{{- with .Values.scheduler.services.internal.annotations }}
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.scheduler.services.internal.type }}
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: worker-sched
    - port: 5049
      targetPort: 5049
      protocol: TCP
      name: obser-grpc
  selector:
    {{- include "polars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
