apiVersion: v1
kind: Service
metadata:
  name: {{ include "polars.scheduler.fullname" . }}
  labels:
    {{- include "polars.labels" . | nindent 4 }}
  annotations:
{{- with .Values.scheduler.services.scheduler.annotations }}
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.scheduler.services.scheduler.type }}
  ports:
    - port: 5051
      targetPort: 5051
      protocol: TCP
      name: sched
  selector:
    {{- include "polars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
