name: Verify Helm documentation

on:
  - pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: azure/setup-helm@v4.3.1

      - name: Install helm-docs
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: norwoodj/helm-docs

      - name: Run generate-helm-docs.sh
        run: |
          ./generate-helm-docs.sh
        shell: bash

      - name: Files changed
        run: |
          git diff --exit-code
        shell: bash
